### ISSUE TITLE
[now deploy] MongoNetworkError: failed to connect to server [ds333098.mlab.com:33098]

### ISSUE THREAD

**Issue by min9nim** [min9nim/little-jesus-api#2]
now 배포 후 외부 디비로 접속을 못하는 오류

```
2019-10-10T15:59:13.250Z	d4f8588d-5d50-4edf-aa8d-9d59980f320f	DB connection error: { MongoNetworkError: failed to connect to server [ds333098.mlab.com:33098] on first connect [MongoNetworkError: connection timed out]
    at Pool.<anonymous> (/var/task/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at connect (/var/task/node_modules/mongodb/lib/core/connection/pool.js:580:14)
    at makeConnection (/var/task/node_modules/mongodb/lib/core/connection/connect.js:39:11)
    at callback (/var/task/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.err (/var/task/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
2019-10-10T15:59:13.253Z	d4f8588d-5d50-4edf-aa8d-9d59980f320f	Unhandled rejection: { MongoNetworkError: failed to connect to server [ds333098.mlab.com:33098] on first connect [MongoNetworkError: connection timed out]
    at Pool.<anonymous> (/var/task/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at connect (/var/task/node_modules/mongodb/lib/core/connection/pool.js:580:14)
    at makeConnection (/var/task/node_modules/mongodb/lib/core/connection/connect.js:39:11)
    at callback (/var/task/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.err (/var/task/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
Duration: 31.71 ms  Billed Duration: 100 ms  Memory Size: 3008 MB  Max Memory Used: 116 MB	
RequestId: f7c34772-4b70-4b31-a036-545e4093f754 Process exited before completing request
```

https://zeit.co/min/little-jesus-api/azh2778p0

**Comment by min9nim** [comment]
그런데 배포된 앱 실행하는데 `/var/task/node_modules/mongodb` 이쪽 로직을 왜 타지?

**Comment by min9nim** [comment]
now.json 은 아래와 같이 세팅하는 것이 맞는거 같음..

```
{
  "public": true,
  "version": 2,
  "builds": [{ "src": "dist/**/*.js", "use": "@now/node" }],
  "routes": [
    {
      "src": "/",
      "dest": "/dist/src/index.js",
      "methods": ["POST", "OPTIONS", "GET"],
      "headers": {
        "Access-Control-Allow-Origin": "*"
      }
    }
  ]
}
```

**Comment by min9nim** [comment]
now 배포시 빌드가 정상적으로 수행되는 것 같지가 않음

배포전에 `yarn build` 후에 배포를 해야 뭔가 변경사항이 반영 되는 것 같음

**Comment by min9nim** [comment]
src/index.ts 에서 `startDB()` 함수를 주석처리 하니 일단 위와 같이 몽고디비 접속 오류는 사라졌다

**Comment by min9nim** [comment]
오!

아폴로 서버 옵션을 아래와 같이 주니까 https://little-jesus-api.min1.now.sh 로 접속시 일단 플레이그라운드가 열렸다!
```javascript
const server = new ApolloServer({typeDefs, resolvers, introspection: true, playground: true})
```

**Comment by min9nim** [comment]
오잉? 머지? 갑자기 디비 연결이 되었다!

![image](https://user-images.githubusercontent.com/6068828/66649662-bc840280-ec69-11e9-841a-9520e4104daa.png)
